### ISSUE TITLE
Implementation of `download zip` feature 

### ISSUE THREAD

**Issue by winterrdog** [alok8bb/cloneit#3]
Hey @alok8bb, 
 How did you intend to implement the `download zip` feature? 
- [ ] My Case 1:
 Is the program supposed to download a `zip` archive that's already hosted on GitHub?

- [ ] My Case 2:
 Is the program `zip` archiving the files to be downloaded on the fly?

How would you want it implemented? 

Looking forward to your response! 🙂

**Comment by alok8bb** [comment]
Hello @winterrdog

The tool is supposed to download the files/subdirectories from that URL to a temp directory in the system, zip it and move to work dir.
Or we can create a custom backend for zipping the files before downloading, that works as well. 

I'm currently a little busy with my studies so I might not be able to contribute. If you want to, you can implement it in any way you like :)

**Comment by winterrdog** [comment]
Hey @alok8bb, thanks for the response. I'll try to implement it since I've got some free time. Surely, I'll be sending in a PR soon with more changes for review🤝. 

Great luck in your studies too👍

**Comment by alok8bb** [comment]
Thanks 😀
