### ISSUE TITLE
Make a package for termux, building is both time + resource consuming 

### ISSUE THREAD

**Issue by rihaq** [alok8bb/cloneit#5]
Instruction  can be found in termux/termux-packages repo wiki

**Comment by T-Dynamos** [comment]
Also include a lisence

**Comment by winterrdog** [comment]
> Also include a lisence 

Done

**Comment by T-Dynamos** [comment]
Yes, You can install in termux with `apt install cloneit`

**Comment by rihaq** [comment]
Ok
