### ISSUE TITLE
Feature Request: Define Download path 

### ISSUE THREAD

**Issue by shihaamabr** [alok8bb/cloneit#6]
Please allow to set download dir as 2nd argument in this format
`cloneit <git url> <download path>`

eg: to download install.sh in current dir
`cloneit https://github.com/alok8bb/cloneit/blob/master/install.sh .`

**Comment by alok8bb** [comment]
Hey @shihaamabr , Thanks for your suggestion. I have implemented this feature in latest [commit](https://github.com/alok8bb/cloneit/commit/62c433f0b1c54a977d585f3b84b8c43213095474). 

Now you can clone a directory to a path say `.` or a custom directory for example. Specifying custom filename for a single file does not work, it'll rather create a new directory with that name and clone file there.
