### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by NotAShelf** [alok8bb/cloneit#7]
Hey! I recently ported this package to the Arch User Repository (AUR) for people to be able to download it easily. As the package is licensed with MIT, I assumed you would be fine with it. But letting you know in case if you have any objections/suggestions.

The package can be found [here](https://aur.archlinux.org/packages/cloneit-git).
Cheers.

**Comment by winterrdog** [comment]
Thanks a lot @NotAShelf 🙏 we appreciate your effort towards this project. 

Lemme take a look at it🤝😁

**Comment by winterrdog** [comment]
> Hey! I recently ported this package to the Arch User Repository (AUR) for people to be able to download it easily. As the package is licensed with MIT, I assumed you would be fine with it. But letting you know in case if you have any objections/suggestions.
> 
> The package can be found [here](https://aur.archlinux.org/packages/cloneit-git).
> Cheers.

So far so good 👍 😊

**Comment by alok8bb** [comment]
Thanks @NotAShelf for porting it to AUR, it looks fine to me. :)
